name: Part One
on:
  pull_request_target:
    types: [ opened, synchronize,]

jobs:
  get-hash:
    runs-on: ubuntu-latest
    steps:
      - name: get commit hashes
        shell: bash
        id: get-commit-hashes
        env:
          BASE_HASH: ${{ github.event.pull_request.base.sha }}
          HEAD_HASH: ${{ github.event.pull_request.head.sha }}
        run: |
          echo "${BASE_HASH} -- ${HEAD_HASH}""
