name: On PR
on: workflow_dispatch

jobs:
  get-matrix:
    name: Testing passing matrices around
    runs-on: ubuntu-latest
    outputs:
      dependencies: ${{ steps.get-matrix.outputs.dependencies }}
    steps:
      - name: Get Matrix
        id: get-matrix
        uses: benlloydjones/actions-test/.github/actions/return-a-matrix@main
  use-matrix:
    name: Use the created matrix
    runs-on: ubuntu-latest
    needs: get-matrix
    strategy:
      matrix:
        dependency: ${{ fromJson(needs.get-matrix.outputs.dependencies )}}
    steps:
      - name: expose values of matrix
        env:
          name: ${{ matrix.dependency.name }}
          currentVersion: ${{ matrix.dependency.currentVersion }}
          updatedVersion: ${{ matrix.dependency.updatedVersion }}
          filePrefix: ${{ matrix.dependency.filePrefix }}
        run: |
         echo ${name}
         echo ${currentVersion}
         echo ${updatedVersion}
         echo ${filePrefix}
