name: On PR
on:
  pull_request_target:
    types: [ opened, synchronize, reopened ]

jobs:
  build-charts:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout PR latest commit
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_requst.head.sha }}
          path: pr
          fetch-depth: 0
      - name: Checkout main
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pusll_request.base.sha }}
          path: target
          fetch-depth: 0
      - name: Get updated versions
        shell: bash
        run: |
          ls -al
          cat target/helm/tigera-operator/calico/Chart.yaml
          cat pr/helm/tigera-operator/calico/Chart.yaml
          CHANGED_VERSIONS=$(diff --recursive target pr | grep "version:" || true)
          echo ${CHANGED_VERSIONS}
