name: On PR
on:
  pull_request_target:
    types: [ opened, synchronize, reopened ]

jobs:
  build-charts:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout PR latest commit
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          path: pr
          fetch-depth: 0
      - name: Checkout main
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.base.sha }}
          path: target
          fetch-depth: 0
      - name: Get updated versions
        id: get-updated-versions
        shell: bash
        run: |
          ls -al
          cat target/helm/tigera-operator/calico/Chart.yaml
          cat pr/helm/tigera-operator/calico/Chart.yaml
          CHANGED_VERSIONS=$(diff --recursive target pr | grep "version:" || true)
          echo "changed_versions=${CHANGED_VERSIONS}" >> "$GITHUB_OUTPUT"
      - name: expose updated versions
        shell: bash
        run: |
          echo "Echoing output:"
          echo ${{ steps.get-updated-versions.outputs.changed_versions }}
