name: On PR
on:
  pull_request_target:
    types: [ opened, synchronize, reopened ]

jobs:
  get-hash:
    runs-on: ubuntu-latest
    steps:
      - name: check out PR
        uses: actions/checkout@v4
        with:
            ref: ${{ github.event.pull_request.head.sha }}
            path: pr
            fetch-depth: 0
      - name: get commit hashes
        shell: bash
        id: get-commit-hashes
        env:
          BASE_HASH: ${{ github.event.pull_request.base.sha }}
          HEAD_HASH: ${{ github.event.pull_request.head.sha }}
        run: |
          WORKING_DIRECTORY=$(pwd)
          cd pr
          GIT_CHANGED=$(git diff "${BASE_HASH}" "${HEAD_HASH}" --name-only)
          echo ${GIT_CHANGED}
          CHANGED_DIR=$($GIT_CHANGED | xargs dirname | sort | uniq)
          echo ${CHANGED_DIR}
          cd ${WORKING_DIRECTORY}
          echo pwd