name: On PR
on:
  pull_request_target:
    types: [ opened, synchronize, reopened ]

jobs:
  get-hash:
    runs-on: ubuntu-latest
    steps:
      - name: check out PR
        uses: actions/checkout@v4
        with:
            ref: ${{ github.event.pull_request.head.sha }}
            path: pr
            fetch-depth: 0
      - name: get commit hashes
        shell: bash
        id: get-commit-hashes
        env:
          BASE_HASH: ${{ github.event.pull_request.base.sha }}
          HEAD_HASH: ${{ github.event.pull_request.head.sha }}
        run: |
          WORKING_DIRECTORY=$(pwd)
          cd pr
          CHANGED_DIR=$(git diff "${BASE_HASH}" "${HEAD_HASH}" --name-only | xargs dirname | sort | uniq)
          echo ${CHANGED_DIR}
          cd ${WORKING_DIRECTORY}
          echo pwd
      - name: create list
        id: create-list
        shell: bash
        run: |
          FILE_ONE="DIR/FILE/ONE"
          FILE_TWO="DIR/FILE/TWO"
          FILES=("${FILE_ONE}" "${FILE_TWO}")
          echo ${FILES[0]}
          echo ${FILES[1]}
          echo "FILES_STRING=${FILES[@]}" >> "$GITHUB_OUTPUT"
      - name: expose list
        id: expose-list
        shell: bash
        env:
          FILES_STRING: ${{ steps.create-list.outputs.files_string }}
        run: |
          IFS=' ' read -r -a FILES <<< $FILES_STRING
          echo ${FILES[0]}
          echo ${FILES[1]}
          echo ${FILES[@]}
      - name: create cluster
        uses: helm/kind-action@v1.10.0
        with:
          kubectl_version: v1.29.4
          node_image: kindest/node:v1.29.4
      - name: do a helm
        shell: bash
        run: |
          helm create test-chart
          helm template ./test-chart --output-dir ./here
