name: On PR
on:
  pull_request_target:
    types: [opened, reopened, synchronize]

permissions:
  contents: read
  id-token: write

jobs:
  build-charts:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout PR latest commit
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          path: pr
          fetch-depth: 0
      - name: Checkout main
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.base.sha }}
          path: target
          fetch-depth: 0
      - name: Get updated versions
        id: get-updated-versions
        shell: bash
        run: |
          CHANGED_VERSIONS=$(diff --recursive target pr | grep "version:" || true)
          echo "changed_versions=${CHANGED_VERSIONS//$'\n'/ }" >> "$GITHUB_OUTPUT"
      - name: expose updated versions
        id: share-hyphen
        shell: bash
        env:
          CHANGED_VERSIONS: ${{ steps.get-updated-versions.outputs.changed_versions }}
        run: |
          echo "Echoing output:"
          echo ${CHANGED_VERSIONS}
      - name: get changed dir
        id: get-changed-dir
        shell: bash
        env:
          BASE_HASH: ${{ github.event.pull_request.base.sha }}
          HEAD_HASH: ${{ github.event.pull_request.head.sha }}
        run: |
          WORKDING_DIR=$(pwd)
          cd pr
          CHANGED_DIR=$(git diff --merge-base "${BASE_HASH}" "${HEAD_HASH}" --name-only | xargs dirname | sort | uniq)
          echo $CHANGED_DIR
          echo "changed_dir=${CHANGED_DIR}" >> "${GITHUB_OUTPUT}"
          cd ${WORKING_DIR}
      - name: generate list of helm values files
        id: generate-values-files
        shell: bash
        env:
          CHANGED_DIR: ${{ steps.get-changed-dir.outputs.changed_dir }}
        run: |
          cd pr
          cd $CHANGED_DIR

          VALUES_FILES=()
          GENERIC_VALUES_FILE=""
          PROD_VALUES_FILE=""
          TEST_VALUES_FILE=""
          DEV_VALUES_FILE=""

          get_values_file () {
            VALUES_FILE=$(ls | grep $1 || true)
            echo $VALUES_FILE
          }

          GENERIC_VALUES_FILE=$(get_values_file "values.yaml")
          PROD_VALUES_FILE=$(get_values_file "pay-prod.yaml")
          TEST_VALUES_FILE=$(get_values_file "pay-test.yaml")
          DEV_VALUES_FILE=$(get_values_file "pay-dev.yaml")

          echo $GENERIC_VALUES_FILE
          echo $PROD_VALUES_FILE
          echo $TEST_VALUES_FILE
          echo $DEV_VALUES_FILE