name: Part Two
on:
  workflow_call:

jobs:
  get-secret:
    outputs:
      the_secret: ${{ steps.get-secret.outputs.secret }}
    runs-on: ubuntu-latest
    steps:
      - name: Get Secret
        id: get-secret
        run: echo "secret=fart" >> "$GITHUB_OUTPUT"
  call-two-with-secret:
    needs: get-secret
    uses: benlloydjones/github_actions/.github/workflows/three.yaml
    with:
      the_secret: ${{ needs.get-secret.outputs.the_secret }}
